CREATE DATABASE MEENA;
use meena;
CREATE TABLE T1(letter text);
INSERT INTO T1 VALUES('A'), ('B'), ('C');
SELECT * FROM T1;

CREATE TABLE T2(number text);
INSERT INTO T2 VALUES(1), (2), (3);
SELECT * FROM T2;

SELECT * FROM T1 CROSS JOIN T2;

-- example 2
CREATE TABLE BLOODGROUP(GROUP_NAME TEXT);
CREATE TABLE RH(RH_NAME TEXT);

INSERT INTO BLOODGROUP VALUES('A'), ('B'), ('AB'), ('O');
INSERT INTO RH VALUES('+'), ('-');

SELECT * FROM BLOODGROUP;
SELECT * FROM RH;

SELECT * FROM BLOODGROUP CROSS JOIN RH;
SELECT  CONCAT(X.GROUP_NAME, Y.RH_NAME) 
        FROM BLOODGROUP X 
        CROSS JOIN RH Y;
        
SELECT  CONCAT(X.GROUP_NAME, Y.RH_NAME) AS bloodgroup
        FROM BLOODGROUP X 
        CROSS JOIN RH Y;
        
-- example 3
CREATE TABLE SIZE(SIZE_NUMBER TEXT);
CREATE TABLE COLOR(COLOR_NAME TEXT);

INSERT INTO SIZE VALUES('S'), ('M'), ('L'), ('XL'), ('XXL');
INSERT INTO COLOR VALUES('RED'), ('BLUE'), ('BLACK');

SELECT * FROM SIZE;
SELECT * FROM COLOR;

-- without concat
SELECT X.SIZE_NUMBER, Y.COLOR_NAME 
       FROM SIZE X 
       CROSS JOIN COLOR Y;

-- concat        
SELECT CONCAT(X.SIZE_NUMBER, Y.COLOR_NAME) AS dress
       FROM SIZE X 
       CROSS JOIN COLOR Y;
       
-- to create space b/w to values
 SELECT CONCAT_WS('_', X.SIZE_NUMBER, Y.COLOR_NAME) AS dress   
       FROM SIZE X 
       CROSS JOIN COLOR Y; 
       
